import { Leaf, List, Mail, MapPin, Search, SlidersHorizontal, Sparkles, Sprout, Wind, Loader2, Store, ShoppingBag, BookOpen, Target, Lightbulb, TrendingUp, Package, PlusCircle, Star, ArrowRight, Boxes, AreaChart, ThumbsUp, ThumbsDown, ChevronDown, Inbox, Handshake } from 'lucide-react';

export const Icons = {
  logo: Leaf,
  list: List,
  mail: Mail,
  mapPin: MapPin,
  search: Search,
  filters: SlidersHorizontal,
  ai: Sparkles,
  ethical: Sprout,
  wind: Wind,
  spinner: Loader2,
  store: Store,
  looseLeaf: Leaf,
  teaware: ShoppingBag,
  classes: BookOpen,
  problem: Target,
  solution: Lightbulb,
  vision: TrendingUp,
  order: Package,
  plusCircle: PlusCircle,
  star: Star,
  arrowRight: ArrowRight,
  types: Boxes,
  analytics: AreaChart,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  chevronDown: ChevronDown,
  inbox: Inbox,
  handshake: Handshake,
};
